FROM ubuntu:latest



# Install curl and Java

RUN apt-get update && \

    apt-get install -y wget && \

    apt-get install -y default-jdk



# Create Tomcat directory

RUN mkdir /opt/tomcat



# Set working directory

WORKDIR /opt/tomcat



# Download and extract Tomcat

ADD https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.86/bin/apache-tomcat-8.5.86.tar.gz .

RUN tar -xvzf apache-tomcat-8.5.86.tar.gz && \

    mv apache-tomcat-8.5.86/* /opt/tomcat && \

    rm -rf apache-tomcat-8.5.86.tar.gz apache-tomcat-8.5.86



# Expose port 8080

EXPOSE 8080



# Start Tomcat

CMD ["bin/catalina.sh", "run"]

# Add Executable war to image

COPY ./*.war /opt/tomcat/webapps 
